#!/bin/bash
set -xe
branch=${TRAVIS_BRANCH}
rsync -e "ssh -i /tmp/ssh/01_deploy -p 22022" -ar shippable/ shippable@demokracia.rulez.org:/var/www/adadocs/ep/$BUILD_NUMBER
ssh -i /tmp/ssh/01_deploy -p 22022 shippable@demokracia.rulez.org "ln -sf /var/www/adadocs/ep/$BUILD_NUMBER /var/www/adadocs/ep/$branch"
