#!/bin/bash
set -xe
branch=${TRAVIS_BRANCH}
mkdir -p shippable/$branch
#mv doc/* shippable/$branch
rsync -e "ssh -i /tmp/ssh/01_deploy -p 22022" -ar shippable/ shippable@demokracia.rulez.org:/var/www/adadocs/ep
