#!/bin/bash
set -xe
wp --allow-root --path=/var/www/wordpress/ user delete bob --reassign=1|| true
wp --allow-root --path=/var/www/wordpress/ post delete $(wp --allow-root --path=/var/www/wordpress/ post list --post_name=alapito-okirat --format=ids) || true
bobid=$(wp --allow-root --path=/var/www/wordpress/ user create bob bob@example.com --user_pass=bobpassword --porcelain)
wp --allow-root --path=/var/www/wordpress/ post create --post_type=post --post_title='Alapito' --post_status=publish --post_name=alapito-okirat etc/alapito-okirat

